主要部分翻譯
SlimeTraditionalTranslation/DankTech2 pull request #1
Opened 2021-12-17 15:48 UTC by xwinhyukx

此更新尚未經過測試

以下部分暫時未完成
- [ ] DankTech2.java 程式碼未修正 - ->@xMikux 這個可能需要交給你
- [ ] README.md

2021-12-17 15:49 UTC, xMikux requested changes

2021-12-17 15:49 UTC, xMikux commented on src/main/java/io/github/sefiraat/danktech2/slimefun/Packs.java
> +                "A 丹克盒 can hold many items",
缺失翻譯

2021-12-17 16:16 UTC, xwinhyukx commented
最後,等待審核.

2021-12-17 17:22 UTC, xMikux requested changes

2021-12-17 17:22 UTC, xMikux commented on src/main/java/io/github/sefiraat/danktech2/core/DankGUI.java
> +            MessageFormat.format("{0}右鍵點擊: {1}收回堆棧", ThemeType.CLICK_INFO.getColor(), ThemeType.PASSIVE.getColor()),
stack 是組

2021-12-17 17:22 UTC, xMikux commented on src/main/java/io/github/sefiraat/danktech2/listeners/PackListener.java
> +                    "{0}丹克包已被欺騙或刪除. 刪除",
duped 是複製
Removing 刪除中

2021-12-17 17:22 UTC, xMikux commented on src/main/java/io/github/sefiraat/danktech2/listeners/PickupListener.java
> +                "{0}你的丹克包已被欺騙或刪除. 刪除",
duped 是複製
Removing 刪除中

2021-12-17 17:37 UTC, xMikux requested changes

2021-12-17 17:37 UTC, xMikux commented on README.md
> +* 共有9個等級垃圾包,其中有更多欄位,但不存儲任何物品,只會使它們全部失效！
Void 是虛空

2021-12-17 17:37 UTC, xMikux commented on README.md
> +* 撤回物品 1,按組,按完整庫存
一個物品, 一組物品, 整個背包

2021-12-17 17:38 UTC, xMikux requested changes

2021-12-17 17:38 UTC, xMikux commented on README.md
> +* 使用丹克的積木來建造
使用丹克包內的方塊來建造

2021-12-17 17:43 UTC, xMikux requested changes

2021-12-17 17:43 UTC, xMikux commented on src/main/java/io/github/sefiraat/danktech2/core/AdminGUI.java
> +        lore.add(MessageFormat.format("{0}和卸貨機", ThemeType.ERROR.getColor()));
卸載機

2021-12-17 17:43 UTC, xMikux commented on src/main/java/io/github/sefiraat/danktech2/core/AdminGUI.java
> +        lore.add(MessageFormat.format("{0}最後用戶: {1}{2}", ThemeType.CLICK_INFO.getColor(), ThemeType.PASSIVE.getColor(), dankPackInstance.getLastUser()));
User 使用者

2021-12-17 17:43 UTC, xMikux commented on src/main/java/io/github/sefiraat/danktech2/core/DankGUI.java
> +        super("丹克盒 - 等級 " + packInstance.getTier());
Pack 包

2021-12-17 17:43 UTC, xMikux commented on src/main/java/io/github/sefiraat/danktech2/core/DankGUI.java
> +            MessageFormat.format("{0}左鍵點擊: {1}收回一個", ThemeType.CLICK_INFO.getColor(), ThemeType.PASSIVE.getColor()),
Withdraw 提取

2021-12-17 17:45 UTC, xMikux requested changes

2021-12-17 17:45 UTC, xMikux commented on src/main/java/io/github/sefiraat/danktech2/core/AdminGUI.java
> +        MessageFormat.format("{0}頁面返回", ThemeType.PASSIVE.getColor())
上一頁

2021-12-17 17:45 UTC, xMikux commented on src/main/java/io/github/sefiraat/danktech2/core/AdminGUI.java
> +        MessageFormat.format("{0}翻頁", ThemeType.PASSIVE.getColor())
下一頁

2021-12-18 03:34 UTC, xMikux requested changes

2021-12-18 03:34 UTC, xMikux commented on README.md
> +* 輸入庫存中所有匹配的項目
背包
物品

2021-12-18 03:34 UTC, xMikux commented on README.md
> +* 一個漂亮的貨物兼容卸載器
cargo 是物流

2021-12-18 03:34 UTC, xMikux commented on src/main/java/io/github/sefiraat/danktech2/core/DankGUI.java
> +            MessageFormat.format("{0}Shift+左鍵點擊: {1}輸入整個庫存", ThemeType.CLICK_INFO.getColor(), ThemeType.PASSIVE.getColor()),
Inventory 物品欄

2021-12-18 05:27 UTC, xMikux requested changes

2021-12-18 05:27 UTC, xMikux commented on src/main/java/io/github/sefiraat/danktech2/slimefun/Machines.java
> +                "丹克工匠",
這個可以翻成 丹克製作台

2021-12-18 05:27 UTC, xMikux commented on src/main/java/io/github/sefiraat/danktech2/slimefun/Machines.java
> +                "工匠和升級丹克背包."
製作和升級

2021-12-18 05:27 UTC, xMikux commented on src/main/java/io/github/sefiraat/danktech2/slimefun/Machines.java
> +                "從你丹克的背包取出物品"
丹克包

2021-12-18 05:27 UTC, xMikux commented on src/main/java/io/github/sefiraat/danktech2/slimefun/Materials.java
> +                "丹克的細胞 - 等級 1",
丹克 的 細胞
的 可以去掉

2021-12-18 05:27 UTC, xMikux commented on src/main/java/io/github/sefiraat/danktech2/slimefun/Packs.java
> +                "一個丹克的背包可以裝很多東西",
丹克包

2021-12-18 05:27 UTC, xMikux commented on src/main/java/io/github/sefiraat/danktech2/slimefun/Packs.java
> +                "一個丹克的背包可以裝很多東西",
丹克包

2021-12-18 06:01 UTC, xMikux requested changes

2021-12-18 06:01 UTC, xMikux commented on src/main/java/io/github/sefiraat/danktech2/slimefun/machines/DankCrafter.java
> +            "在丹克的工匠中製作"
丹克製作台

2021-12-18 06:04 UTC, xMikux requested changes

2021-12-18 06:04 UTC, xMikux commented on src/main/java/io/github/sefiraat/danktech2/slimefun/Machines.java
> +                "從你丹克包取出物品"
你的

2021-12-18 13:36 UTC, xMikux approved these changes

2021-12-18 13:39 UTC, weiii-joe approved these changes

2021-12-18 13:40 UTC, merged